### ISSUE TITLE
Why are items casted to strings in runTolerantSingleCommand()?

### ISSUE THREAD

**Issue by andreas-gruenwald** [webmozarts/console-parallelization#27]
Why are items casted to strings in https://github.com/webmozarts/console-parallelization/blob/master/src/Parallelization.php#L367?

In my use-cases an item is an array or a data object, which we have to serialize into a string, e.g. by applying ``serialize()``, and afterwards unserializing the data in ``runSingleCommand()``.

Probably the serialization/unserialization part could be done by the trait out of the box?

**Comment by webmozart** [comment]
@andreas-gruenwald The reason is the communication between the master and the child processes. The master processes pipes all elements through STDIN of the child process, and that communication naturally is in clear text.

Calling `serialize()` and `unserialize()` is the way to go in your case. The reason why this is not done automagically is that it should be clear to the developer what's happening behind the scenes so that they make wise choices regarding "what is an item".

For example, serializing/unserializing database objects has a negative performance impact, since the communication through STDIN is comparatively slow. It's better to transfer the ID of the object and fetch it in the child process instead.

**Comment by andreas-gruenwald** [comment]
Good explanation! We can close the issue.
