### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by andreas-gruenwald** [webmozarts/console-parallelization#39]
Hi guys,
I just want to thank you for that amazing bundle, which is very likely to be part of [Pimcore](http://pimcore.org/) soon!  
🎉🎉🎉

That's why I want to ask if there already exists a (rough) roadmap for the future releases?

- Stable version 1.0 ist out since 2 days, and Pimcore will probably start with that one.
- Version 2.* is already in deployment. When will the next release approximately take place? How likely is it that there are breaking changes?

**Comment by theofidry** [comment]
Hi :)

1.0 is out and whilst not completely happy with it: it's been used that way extensively internally so it makes sense to make it stable. Even more so since it's been a while since the first RC came out.

2.0 is now in development to allow more exotic changes without worrying about BC. There is no approximate release date because it will entirely depend on how much time we can free for it and incoming contributions.

There is 100% going to be breaking changes. How hard/easy is going to be to migrate is hard to say. I would just say we don't fancy to rewrite all our commands from scratch to upgrade internally either so it's unlikely to be crazy.

A few items on my list that are planned for 2.0:

- Capture more cases in the tests (e.g. what environment variables/options are passed to sub-processes; the behaviour when some items of the sub process are processed and the sub-process suddenly dies mid-way or has an error, ...)
- Consider an alternative to the Symfony `Process` for parallelization – if done it should be possible without requiring any change to the consumer
- #26
- Consolidate the codebase (Psalm, infection?)
- More typesafety – maybe a command than can be extended can be provided as well instead of just a trait. The idea of the trait was to allow an easy usage without requiring too much refactoring if you were already extending a sub-command. It however comes with trade-offs and sometimes exnteding a base command may be easily doable

Those are a few things on top of my head. But nothing is set in stone and of course contributions are welcomed
