### ISSUE TITLE
Better solution for the "item" - argument?

### ISSUE THREAD

**Issue by andreas-gruenwald** [webmozarts/console-parallelization#40]
Sometimes you want to provide a custom argument in your command and combine ith with several options.

With the current solution (v1.0.0) it is difficult to add custom arguments as the trait already has an internal "item" argument.

```php
    protected function configure()
    {
        parent::configure();
        $this
            ->setDescription('Processes the preparation and/or update-index queue.')
            ->addArgument('queue', InputArgument::REQUIRED | InputArgument::IS_ARRAY)            
        ;

        self::configureParallelization($this);

 $this
            ->addOption('tenant', null, InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY)
            //...

    }
````

Error:
``Cannot add an argument after an array argument.``

Do you think it is possible to replace the item argument and define it as an option instead?
We need to use the argument as it is because we don't want to break compatibility in Pimcore.

Trait:
````php
            ->addArgument(
                'item',
                InputArgument::OPTIONAL,
                'The item to process'
            )
```

**Comment by theofidry** [comment]
I think having it as an argument makes more sense :/

A workaround though is to fiddle with the `InputDefinition` object. You can retrieve it, get the arguments, replace/remove the one you want and you're good. The API to do so is a bit ugly IIRC but that works and since it's more for a compat layer I think it's ok.

I'm not 100% it will work as it is if you remove the argument (because the argument is no longer registered), but if not I think it's something we could allow here

**Comment by andreas-gruenwald** [comment]
Ok for the moment we can live with that. 
For 2.x it would be great if there would at least some way to override / disable the default arguments.
